# Read the Docs configuration file for DLB
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - autotools-dev
    - autoconf
    - libtool
  jobs:
    pre_build:
    - ./bootstrap
    - ./configure
    - make doxygen
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT/html/ 
        - rm -rf $READTHEDOCS_OUTPUT/html/*
        - make html
        - mv doc/user_guide/html/* $READTHEDOCS_OUTPUT/html
      pdf:
        - mkdir -p $READTHEDOCS_OUTPUT/pdf/ 
        - rm -rf $READTHEDOCS_OUTPUT/pdf/*
        - make pdf
        - mv doc/user_guide/pdf/DLBUserGuide.pdf $READTHEDOCS_OUTPUT/pdf

python:
   install:
   - requirements: doc/user_guide/requirements.txt
